Livraria.WebApplication/Models/ErrorViewModel.cs
using System;

namespace Livraria.WebApplication.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Livraria.WebApplication/Models/LivroViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace Livraria.WebApplication.Models
{
    public class LivroViewModel
    {
        public int Id { get; set; }
        [Required]
        [MaxLength(150)]
        public string Nome { get; set; }
        [Required]
        [MaxLength(150)]
        [Display(Name = "Autor(a)")]
        public string Autor { get; set; }
        [Required]
        public int Quantidade { get; set; }
    }
}

Livraria.WebApplication/Controllers/HomeController.cs
using Livraria.WebApplication.Helper;
using Livraria.WebApplication.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Livraria.WebApplication.Controllers
{
    public class HomeController : Controller
    {
        private const string ACTION_INDEX = "Index";
        private readonly LivrariaApi<LivroViewModel> _api;

        public HomeController()
        {
            _api = new LivrariaApi<LivroViewModel>("api/livraria/livro");
        }

        public async Task<IActionResult> Index()
        {
            var livros = await _api.GetAsync();
            return View(livros.OrderBy(prop => prop.Nome));
        }

        public async Task<IActionResult> Detalhes(int id)
        {
            var livro = await _api.GetAsync(id);
            return View(livro ?? new LivroViewModel());
        }

        public ActionResult NovoLivro()
        {
            return View();
        }

        [HttpPost]
        public IActionResult NovoLivro(LivroViewModel livro)
        {
            var res = _api.PostAsJsonAsync(livro);

            if (res.IsSuccessStatusCode)
                return RedirectToAction(ACTION_INDEX);

            return View();
        }

        [HttpGet]
        public async Task<ViewResult> Editar(int id)
        {
            var livro = await _api.GetAsync(id);
            return View(livro);
        }

        [HttpPost]
        public IActionResult Editar(int id, LivroViewModel livro)
        {
            var res = _api.PutAsJsonAsync(id, livro);
            
            if (res.IsSuccessStatusCode)
            {
                return RedirectToAction(ACTION_INDEX);
            }

            return View();
        }

        public async Task<IActionResult> Excluir(int id)
        {
            await _api.DeleteAsync(id);
            return RedirectToAction(ACTION_INDEX);
        }

        public IActionResult Sobre()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Livraria.WebApplication/Controllers/LivroController.cs
using Livraria.WebApplication.Helper;
using Livraria.WebApplication.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Livraria.WebApplication.Controllers
{
    public class LivroController : Controller
    {
        private const string ACTION_INDEX = "Index";
        private readonly LivrariaApi<LivroViewModel> _api;

        public LivroController()
        {
            _api = new LivrariaApi<LivroViewModel>("api/livraria/livro");
        }

        public async Task<IActionResult> Index()
        {
            var livros = await _api.GetAsync();
            return View(livros.OrderBy(prop => prop.Nome));
        }

        public async Task<IActionResult> Detalhes(int id)
        {
            var livro = await _api.GetAsync(id);
            return View(livro ?? new LivroViewModel());
        }

        public ActionResult NovoLivro()
        {
            return View();
        }

        [HttpPost]
        public IActionResult NovoLivro(LivroViewModel livro)
        {
            var res = _api.PostAsJsonAsync(livro);

            if (res.IsSuccessStatusCode)
                return RedirectToAction(ACTION_INDEX);

            return View();
        }

        [HttpGet]
        public async Task<ViewResult> Editar(int id)
        {
            var livro = await _api.GetAsync(id);
            return View(livro);
        }

        [HttpPost]
        public IActionResult Editar(int id, LivroViewModel livro)
        {
            var res = _api.PutAsJsonAsync(id, livro);
            
            if (res.IsSuccessStatusCode)
            {
                return RedirectToAction(ACTION_INDEX);
            }

            return View();
        }

        public async Task<IActionResult> Excluir(int id)
        {
            await _api.DeleteAsync(id);
            return RedirectToAction(ACTION_INDEX);
        }

        public IActionResult Sobre()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Livraria.WebApplication/Views/Livro/Detalhes.cshtml
@model Livraria.WebApplication.Models.LivroViewModel

@{
    ViewData["Title"] = "Detalhes";
}

<div class="title">@ViewData["Title"]</div>
<hr />
<div>
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Autor)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Autor)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Quantidade)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Quantidade)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Index" class="btn btn-secondary btn-sm"><i class="fa fa-chevron-left "></i> Voltar</a>
</div>

Livraria.WebApplication/Views/Livro/Editar.cshtml
@model Livraria.WebApplication.Models.LivroViewModel

@{
    ViewData["Title"] = "Editar";
}

<div class="title">@ViewData["Title"]</div>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Editar">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Autor" class="control-label"></label>
                <input asp-for="Autor" class="form-control" />
                <span asp-validation-for="Autor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Quantidade" class="control-label"></label>
                <input asp-for="Quantidade" class="form-control" />
                <span asp-validation-for="Quantidade" class="text-danger"></span>
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-primary btn-sm"><i class="fa fa-save"> Salvar</i></button>
                <a asp-action="Index" class="btn btn-secondary btn-sm"><i class="fa fa-chevron-left "></i> Voltar</a>
            </div>
        </form>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Livraria.WebApplication/Views/Livro/Index.cshtml
@model IEnumerable<Livraria.WebApplication.Models.LivroViewModel>

@{
    ViewData["Title"] = "Livros";
}

<link rel="stylesheet" href="https://cdn.datatables.net/1.10.20/css/jquery.dataTables.min.css" />
<script src="~/js/site.js"></script>
<script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
<script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js" defer></script>
<script src="https://cdn.datatables.net/plug-ins/1.10.20/i18n/Portuguese-Brasil.json"></script>

<div class="title">Livros</div>
<p>
    <a asp-action="NovoLivro" class="btn btn-primary btn-sm"><i class="fa fa-plus"></i> Adicionar Livro</a>
</p>
<table id="tabelaLivros" class="table table-striped">
    <thead>
        <tr>
            <th></th>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Autor)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Quantidade)
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.ActionLink("", "Editar", new { id = item.Id }, new { @class = "btn btn-outline-primary btn-sm fa fa-pencil", @title = "Editar" })
                    @Html.ActionLink("", "Detalhes", new { id = item.Id }, new { @class = "btn btn-outline-secondary btn-sm fa fa-book", @title = "Detalhes" })
                    @Html.ActionLink("", "Excluir", new { id = item.Id }, new { @class = "btn btn-outline-danger btn-sm fa fa-minus", @title = "Excluir" })
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Nome)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Autor)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Quantidade)
                </td>
            </tr>
        }
    </tbody>
</table>

Livraria.WebApplication/Views/Livro/NovoLivro.cshtml
@model Livraria.WebApplication.Models.LivroViewModel

@{
    ViewData["Title"] = "Adicionar Livro";
}

<div class="title">@ViewData["Title"]</div>

<hr />
<div class="row">
    <div class="col-md-12">
        <form asp-action="NovoLivro">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Autor" class="control-label"></label>
                <input asp-for="Autor" class="form-control" />
                <span asp-validation-for="Autor" class="text-danger"></span>
            </div>
            <div class="form-group col-md-6 no-paddding">
                <label asp-for="Quantidade" class="control-label"></label>
                <input asp-for="Quantidade" class="form-control" />
                <span asp-validation-for="Quantidade" class="text-danger"></span>
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-primary btn-sm"><i class="fa fa-save"> Salvar</i></button>
                <a asp-action="Index" class="btn btn-secondary btn-sm"><i class="fa fa-chevron-left "></i> Voltar</a>
            </div>
        </form>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Livraria.WebApplication/Views/Livro/Sobre.cshtml
@{
    ViewData["Title"] = "Sobre";
}
<div class="title">@ViewData["Title"]</div>
<hr />
<p>Desenvolvido por Francisco Santana.</p>
<p>Data da última atualização: 16/03/2019</p>

Livraria.WebApplication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Livraria Santana</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/lib/font-awesome/css/font-awesome.min.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" />
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Livro" asp-action="Index">
                    <img src="~/imagens/livro-logo.png" title="Livraria Santana" class="logo"/>
                    Livraria Santana
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Livro" asp-action="Index">Início</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Livro" asp-action="Sobre">Sobre</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Livraria Santana - <a asp-area="" asp-controller="Livro" asp-action="Sobre">Sobre</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>